name: Test

on:
  pull_request:
  push:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      max-parallel: 15
      fail-fast: false
      matrix:
        php-versions: [ '8.2', '8.3', '8.4', '8.5' ]

    name: PHP ${{ matrix.php-versions }}
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          extensions: json, mbstring
          coverage: pcov

      - name: Install dependencies
        run: composer update --no-interaction --prefer-dist --no-suggest --prefer-stable

      - name: Lint composer.json
        run: composer validate --strict

      - name: Run Tests with Coverage
        run: vendor/bin/phpunit -v --coverage-text --coverage-clover=build/logs/clover.xml

      - name: Upload coverage to Codecov
        if: matrix.php-versions == '8.5'
        uses: codecov/codecov-action@v5
        with:
          files: build/logs/clover.xml
          fail_ci_if_error: false
